//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryUsingEFinMVC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTask
    {
        public int EmployeeId { get; set; }
        public int TaskId { get; set; }
        public Nullable<System.DateTime> DateTimeAssigned { get; set; }
        public Nullable<double> CompletionTime { get; set; }
        public Nullable<bool> Completed { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> Finish { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Task Task { get; set; }
    }
}
