//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryUsingEFinMVC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.EmployeeTasks = new HashSet<EmployeeTask>();
        }
    
        public int TaskId { get; set; }
        public string Room { get; set; }
        public string TaskName { get; set; }
        public double EstimatedTime { get; set; }
        public Nullable<double> CompletionTime { get; set; }
        public int PropId { get; set; }
        public string GuidePhotoUrl { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public string TaskType { get; set; }
        public int BuildingId { get; set; }
    
        public virtual Building Building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeTask> EmployeeTasks { get; set; }
    }
}
